### ISSUE TITLE
Code is blocking other remotes

### ISSUE THREAD

**Issue by kopierschnitte** [jens62/geberit-aquaclean#1]
Thanks for your code. It works and I could successfully connect ;-)

Unfortunately, the toilet allows only one parallel connection and therefore, any existing remote is useless as long as the code is executing.

Maybe it would be a better idea to not stay connected all the time and rather do a connection "on demand". This would allow custom "buttons" to perform actions on the device while the original remote or app still remains operational.

**Comment by jens62** [comment]
Thank you for your interest and feedback!

Yes, we are dealing with a Highlander WC:
*Es kann nur einen geben!*
*There can be only one!*

See also [GEBERIT AQUACLEAN MERA COMFORT BEDIENUNGSANLEITUNG](https://cdn.data.geberit.com/documents/966.731.00.0_09.pdf), page 20, at the top of the page:

`... Die Fernbedienung des Geberit AquaClean Dusch-WCs ist deaktiviert, solange das Dusch-WC mit
der Geberit Home App verbunden ist. ...`

... and the `aquaclean_console_app` works in the same way as the App.

This seems to be the nature of BLE architecture (at least before BLE 5.0).

I took this information from the article [Wir müssen reden](https://entwickler.de/iot/wir-mussen-reden-002):
`... Dabei kann ein Central durchaus zu mehreren Peripherals eine Verbindung herstellen. Ein Smartphone kann sich also mit mehreren E-Health-Geräten verbinden. Ein Peripheral dagegen kann immer nur mit einem einzigen Central verbunden sein, ein E-Health-Gerät beispielsweise also nicht gleichzeitig mit mehreren Smartphones. Das ist übrigens auch einer der Gründe, warum Sie mit Ihrer Bluetoothtastatur nicht gleichzeitig zwei Rechner steuern können. ...`

or [Can a peripheral can be connected to multiple centrals?](https://stackoverflow.com/a/29571254)


There is always a ‘but’.
Here's the information from Copilot:

## chat with Copilot

`How do I connect a BLE peripheral to multiple central devices?`

A Bluetooth Low Energy (BLE) peripheral device can connect to multiple central devices by using a technique called **multi-connection**. Here's a general overview of how this can be achieved:

1. **Multi-Connection Support**: Ensure that both the BLE peripheral device and the central devices support multi-connection. This feature is typically available in BLE 5.0 and newer versions.

2. **Connection Management**: The BLE peripheral device needs to manage multiple connections by maintaining separate connections with each central device. This can be done by using different connection intervals, connection parameters, and managing the data exchange efficiently.

3. **UUIDs and Services**: Each connection can be identified by unique UUIDs (Universally Unique Identifiers) for services and characteristics. This helps the central device to distinguish between different peripherals.

4. **Sequential or Simultaneous Connections**: Depending on the application, the peripheral device can connect to multiple central devices sequentially (one after the other) or simultaneously (at the same time). Sequential connections are simpler to manage, while simultaneous connections require more complex handling.

5. **Power Management**: Efficient power management is crucial when connecting to multiple central devices. The peripheral device should minimize the time it spends in active connection mode to conserve battery life.

6. **Software Implementation**: Implementing multi-connection typically involves using BLE libraries and APIs that support multi-connection features. For example, using the BLE stack provided by the microcontroller or development board, or using software libraries like BlueZ for Linux.



`Is there a type of hub that can connect to the peripheral device once using BLE 4 and then accept multiple connections using BLE 5?`


Yes, there are devices known as **BLE hubs** or **BLE gateways** that can connect to a BLE peripheral device using BLE 4 and then accept multiple connections through BLE 5. These hubs act as intermediaries, allowing multiple central devices to communicate with the peripheral device.

One example is the **DSGW-030-2 Bluetooth over WiFi Bridge Gateway Hub**. This device connects to BLE peripherals using BLE 4 and then bridges the connection to WiFi, allowing multiple central devices to access the BLE device over the internet.


## Conclusion, tl;dr

For my use cases, I want to avoid any additional operating action. We only use the remote controls/app very rarely and I deactivate the service on my raspberry beforehand.

Anyway, I like to think about an additional operating mode that only connects on request!

**Comment by kopierschnitte** [comment]
So you are already using a different kind of remote (which communicates using HA/MQTT) for regular use?

**Comment by jens62** [comment]
The [aquaclean_console_app](https://github.com/jens62/geberit-aquaclean) runs permanently in the background and manages the integration into the home automation system.

In addition, we have
- [Wandbedienpanel für Geberit AquaClean, EAN 4025416817031](https://catalog.geberit.de/de-DE/product/PRO_231561)
- [Fernbedienung groß, für Geberit AquaClean Mera, old model EAN 4025416432326](https://catalog.geberit.de/de-DE/product/PRO_3191432)
- [Gerberit Home](https://apps.apple.com/de/app/geberit-home/id1445857678)
- 
The three remote controls mentioned above are rarely used.
[aquaclean_console_app](https://github.com/jens62/geberit-aquaclean) is deactivated beforehand.

**Comment by kopierschnitte** [comment]
Okay, but do you actually use the Python code (using your home automation system) for example to open/close the toilet?

I also use the same remotes like you and it sounds a little bit complicated to deactivate the Python app everytime I want to use the toilet. On the other hand, the home automation won't notice any "actions" if the toilet is controlled by one of Geberit's remotes.

Correct me if I'm wrong but basically, one have to use a centralized infrastructure (like Zigbee switches or even NSPanels) to control the toilet exclusively ... and get completely rid of the Geberit devices.

**Comment by jens62** [comment]
1. Yes, I use the Python code to open and close the lid. To do this, I connected the Python script via [MQTT Binding](https://www.openhab.org/addons/bindings/mqtt/) --> [openHAB](https://www.openhab.org) with [HomeKit Add-on](https://www.openhab.org/addons/integrations/homekit/). The toilet lid is then controlled by voice command. See [Use cases](https://github.com/jens62/geberit-aquaclean#use-cases).
2. Yes, I use [openHAB](https://www.openhab.org), see [Geberit AquaClean with openHAB - Basic UI](https://github.com/jens62/geberit-aquaclean/blob/main/operation_support/Geberit%20AquaClean%20with%20openHAB%20-%20Basic%20UI.png), as the central infrastructure ("... and get completely rid of the Geberit devices").

**Comment by kopierschnitte** [comment]
Great ideas. Thanks!
Feel free to close this issue if non-permanent connections are not on your roadmap ;-)

**Comment by jens62** [comment]
👋 Hi there! It looks like you forgot to select an option from one of the dropdown menus (you left it as '--- Please select ---'). 

**Please edit your issue and select the correct OS/Version so we can help you faster!**

**Comment by jens62** [comment]
👋 Hi there! It looks like you forgot to select an option from one of the dropdown menus (you left it as '--- Please select ---'). 

**Please edit your issue and select the correct OS/Version so we can help you faster!**
